name: Static checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install rustup
        run: sudo snap install --classic rustup
      - name: Install Rust toolchain
        run: rustup toolchain install stable --component rustfmt,clippy
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Run static checks
        run: make static-checks
